### ISSUE TITLE
还更新吗  推荐的项目已经移除了

### ISSUE THREAD

**Issue by AmberHan** [Airmole/douyin-wss#2]
https://github.com/YunzhiYike/douyin-live你有这个项目的代码吗  谢谢

**Comment by Airmole** [comment]
> [https://github.com/YunzhiYike/douyin-live你有这个项目的代码吗](https://github.com/YunzhiYike/douyin-live%E4%BD%A0%E6%9C%89%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%E7%9A%84%E4%BB%A3%E7%A0%81%E5%90%97) 谢谢

太久了，我也没有诶

**Comment by AmberHan** [comment]
> > [https://github.com/YunzhiYike/douyin-live你有这个项目的代码吗](https://github.com/YunzhiYike/douyin-live%E4%BD%A0%E6%9C%89%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%E7%9A%84%E4%BB%A3%E7%A0%81%E5%90%97) 谢谢
> 
> 太久了，我也没有诶

好的 谢谢~
